---
- name: Enable user lingering for Syncthing user
  ansible.builtin.command: loginctl enable-linger {{ syncthing_user }}
  changed_when: false

- name: Enable Syncthing user service
  ansible.builtin.systemd:
    name: syncthing@{{ syncthing_user }}
    enabled: true
    state: started
