---
- name: Ensure snapd is enabled and running
  ansible.builtin.systemd:
    name: snapd
    enabled: true
    state: started

- name: Install snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop: "{{ snap_packages_list }}"
